version: "3"
services:
  pricing_app:
    build: ./pricing_app
    ports:
      - '3003:3003'
    volumes:
      - ./pricing_app/:/usr/src/pricing_app
  booking_app:
    build: ./booking_app
    ports: 
      - '3004:3004'
    volumes:
      - ./booking_app/:/usr/src/booking_app
    environment:
      REDIS_URL: redis://redis:6379/0
  buying_app:
    build: ./buying_app
    ports:
      - "3006:3006"
    volumes:
      - ./buying_app/:/usr/src/buying_app
  logging_app:
    build: ./logging_app
    ports:
      - "3007:3007"
    volumes:
      - ./logging_app:/usr/src/logging_app

volumes:
  redis:
  